version: '3.7'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: finctional_db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: "!@opci543A"
    volumes:
      - wordpress_data:/var/www/html
      - .:/var/www/html/wp-content/themes/fictional-university
    networks:
      - wordpress_net

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: finctional_db
      MYSQL_USER: user
      MYSQL_PASSWORD: "!@opci543A"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_net

volumes:
  wordpress_data:
  db_data:

networks:
  wordpress_net:
